In [2]:
import pandas as pd
df_people = pd.read_csv('people.csv')
df_people

   age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [3]:
df_people.drop_duplicates(inplace=True)

In [4]:
print(df_people)

   age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [5]:
df_people.drop_duplicates(subset='nationality')

   age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

In [6]:
df = pd.read_csv('weather.csv')

In [7]:
df

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
0,NaN,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,...,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号
1,2019/12/14,9.3,8,1,15.9,8,1,3.2,8,1,...,1,NaN,0,1,2.0,8,1,8.9,8,1
2,2019/12/15,7.8,8,1,11.1,8,1,4.0,8,1,...,1,NaN,0,1,2.3,8,1,6.3,8,1
3,2019/12/16,6.9,8,1,12.5,8,1,1.3,8,1,...,1,NaN,0,1,1.1,8,1,8.9,8,1
4,2019/12/17,8.2,8,1,10.3,8,1,5.7,8,1,...,1,NaN,0,1,1.1,8,1,0.2,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,2020/12/10,8.7,8,1,11.1,8,1,6.0,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
364,2020/12/11,9.2,8,1,13.8,8,1,3.5,8,1,...,1,NaN,0,1,0.8,8,1,4.3,8,1
365,2020/12/12,10.4,8,1,14.0,8,1,8.0,8,1,...,1,NaN,0,1,1.4,8,1,1.4,8,1
366,2020/12/13,8.6,8,1,14.4,8,1,4.4,8,1,...,1,NaN,0,1,1.0,8,1,5.5,8,1
367,2020/12/14,7.8,8,1,12.2,8,1,4.4,8,1,...,1,NaN,0,1,1.9,8,1,4.4,8,1

In [8]:
df.rename(columns={'平均気温(℃)':'平均気温'})

,年月日,平均気温,平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
0,NaN,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,...,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号
1,2019/12/14,9.3,8,1,15.9,8,1,3.2,8,1,...,1,NaN,0,1,2.0,8,1,8.9,8,1
2,2019/12/15,7.8,8,1,11.1,8,1,4.0,8,1,...,1,NaN,0,1,2.3,8,1,6.3,8,1
3,2019/12/16,6.9,8,1,12.5,8,1,1.3,8,1,...,1,NaN,0,1,1.1,8,1,8.9,8,1
4,2019/12/17,8.2,8,1,10.3,8,1,5.7,8,1,...,1,NaN,0,1,1.1,8,1,0.2,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,2020/12/10,8.7,8,1,11.1,8,1,6.0,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
364,2020/12/11,9.2,8,1,13.8,8,1,3.5,8,1,...,1,NaN,0,1,0.8,8,1,4.3,8,1
365,2020/12/12,10.4,8,1,14.0,8,1,8.0,8,1,...,1,NaN,0,1,1.4,8,1,1.4,8,1
366,2020/12/13,8.6,8,1,14.4,8,1,4.4,8,1,...,1,NaN,0,1,1.0,8,1,5.5,8,1
367,2020/12/14,7.8,8,1,12.2,8,1,4.4,8,1,...,1,NaN,0,1,1.9,8,1,4.4,8,1

In [13]:
df.columns = ['年月日', 
              '平均気温', 
              '最高気温', 
              '最低気温', 
              '降水量の合計', 
              '最深積雪', 
              '平均雲量', 
              '平均蒸気圧', 
              '平均風速', 
              '日照時間']

ValueError: Length mismatch: Expected axis has 28 elements, new values have 10 elements

In [14]:
df

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
0,NaN,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,...,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号
1,2019/12/14,9.3,8,1,15.9,8,1,3.2,8,1,...,1,NaN,0,1,2.0,8,1,8.9,8,1
2,2019/12/15,7.8,8,1,11.1,8,1,4.0,8,1,...,1,NaN,0,1,2.3,8,1,6.3,8,1
3,2019/12/16,6.9,8,1,12.5,8,1,1.3,8,1,...,1,NaN,0,1,1.1,8,1,8.9,8,1
4,2019/12/17,8.2,8,1,10.3,8,1,5.7,8,1,...,1,NaN,0,1,1.1,8,1,0.2,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,2020/12/10,8.7,8,1,11.1,8,1,6.0,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
364,2020/12/11,9.2,8,1,13.8,8,1,3.5,8,1,...,1,NaN,0,1,0.8,8,1,4.3,8,1
365,2020/12/12,10.4,8,1,14.0,8,1,8.0,8,1,...,1,NaN,0,1,1.4,8,1,1.4,8,1
366,2020/12/13,8.6,8,1,14.4,8,1,4.4,8,1,...,1,NaN,0,1,1.0,8,1,5.5,8,1
367,2020/12/14,7.8,8,1,12.2,8,1,4.4,8,1,...,1,NaN,0,1,1.9,8,1,4.4,8,1

In [17]:
df = df.sort_values('平均気温(℃)', ascending=False)

In [18]:
df

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
246,2020/8/15,31.2,8,1,36.5,8,1,27.8,8,1,...,1,NaN,0,1,1.5,8,1,8.7,8,1
248,2020/8/17,30.9,8,1,37.2,8,1,26.8,8,1,...,1,NaN,0,1,1.7,8,1,9.4,8,1
244,2020/8/13,30.4,8,1,37.1,8,1,26.9,8,1,...,1,NaN,0,1,1.6,8,1,8.5,8,1
243,2020/8/12,30.3,8,1,35.9,8,1,27.6,8,1,...,1,NaN,0,1,1.8,8,1,7.2,8,1
260,2020/8/29,30.0,8,1,34.3,8,1,27.4,8,1,...,1,NaN,0,1,2.3,8,1,11.2,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2020/2/10,3.6,8,1,8.8,8,1,-2.2,8,1,...,1,NaN,0,1,1.1,8,1,6.5,8,1
58,2020/2/9,3.1,8,1,7.5,8,1,-0.2,8,1,...,1,NaN,0,1,2.3,8,1,10.1,8,1
55,2020/2/6,2.3,8,1,5.5,8,1,-1.3,8,1,...,1,NaN,0,1,3.6,8,1,7.5,8,1
56,2020/2/7,1.8,8,1,7.0,8,1,-4.3,8,1,...,1,NaN,0,1,1.1,8,1,6.7,8,1
0,NaN,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,...,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号

In [23]:
pd.get_dummies(df_people, columns=['nationality'])

,age,id,name,nationality_America,nationality_Japan,nationality_Korea
0,26,13,Imanishi,0,1,0
1,21,33,Mike,1,0,0
2,35,31,Suzuki,0,1,0
3,16,20,John,1,0,0
4,28,11,Kim,0,0,1

In [25]:
df.isnull()

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
246,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
248,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
244,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
243,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
260,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
0,True,True,False,False,True,False,False,True,False,False,...,False,True,False,False,True,False,False,True,False,False

In [26]:
df.fillna(0)

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
246,2020/8/15,31.2,8,1,36.5,8,1,27.8,8,1,...,1,0.0,0,1,1.5,8,1,8.7,8,1
248,2020/8/17,30.9,8,1,37.2,8,1,26.8,8,1,...,1,0.0,0,1,1.7,8,1,9.4,8,1
244,2020/8/13,30.4,8,1,37.1,8,1,26.9,8,1,...,1,0.0,0,1,1.6,8,1,8.5,8,1
243,2020/8/12,30.3,8,1,35.9,8,1,27.6,8,1,...,1,0.0,0,1,1.8,8,1,7.2,8,1
260,2020/8/29,30.0,8,1,34.3,8,1,27.4,8,1,...,1,0.0,0,1,2.3,8,1,11.2,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2020/2/10,3.6,8,1,8.8,8,1,-2.2,8,1,...,1,0.0,0,1,1.1,8,1,6.5,8,1
58,2020/2/9,3.1,8,1,7.5,8,1,-0.2,8,1,...,1,0.0,0,1,2.3,8,1,10.1,8,1
55,2020/2/6,2.3,8,1,5.5,8,1,-1.3,8,1,...,1,0.0,0,1,3.6,8,1,7.5,8,1
56,2020/2/7,1.8,8,1,7.0,8,1,-4.3,8,1,...,1,0.0,0,1,1.1,8,1,6.7,8,1
0,0,0.0,品質情報,均質番号,0.0,品質情報,均質番号,0.0,品質情報,均質番号,...,均質番号,0.0,品質情報,均質番号,0.0,品質情報,均質番号,0.0,品質情報,均質番号

In [28]:
df.fillna({'平均蒸気圧(hPa)': '100'})

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
246,2020/8/15,31.2,8,1,36.5,8,1,27.8,8,1,...,1,100,0,1,1.5,8,1,8.7,8,1
248,2020/8/17,30.9,8,1,37.2,8,1,26.8,8,1,...,1,100,0,1,1.7,8,1,9.4,8,1
244,2020/8/13,30.4,8,1,37.1,8,1,26.9,8,1,...,1,100,0,1,1.6,8,1,8.5,8,1
243,2020/8/12,30.3,8,1,35.9,8,1,27.6,8,1,...,1,100,0,1,1.8,8,1,7.2,8,1
260,2020/8/29,30.0,8,1,34.3,8,1,27.4,8,1,...,1,100,0,1,2.3,8,1,11.2,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2020/2/10,3.6,8,1,8.8,8,1,-2.2,8,1,...,1,100,0,1,1.1,8,1,6.5,8,1
58,2020/2/9,3.1,8,1,7.5,8,1,-0.2,8,1,...,1,100,0,1,2.3,8,1,10.1,8,1
55,2020/2/6,2.3,8,1,5.5,8,1,-1.3,8,1,...,1,100,0,1,3.6,8,1,7.5,8,1
56,2020/2/7,1.8,8,1,7.0,8,1,-4.3,8,1,...,1,100,0,1,1.1,8,1,6.7,8,1
0,NaN,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,...,均質番号,100,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号

In [30]:
df.dropna(axis=1)

,平均気温(℃).1,平均気温(℃).2,最高気温(℃).1,最高気温(℃).2,最低気温(℃).1,最低気温(℃).2,降水量の合計(mm).1,降水量の合計(mm).2,最深積雪(cm).1,最深積雪(cm).2,平均雲量(10分比).1,平均雲量(10分比).2,平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s).1,平均風速(m/s).2,日照時間(時間).1,日照時間(時間).2
246,8,1,8,1,8,1,8,1,0,1,0,1,0,1,8,1,8,1
248,8,1,8,1,8,1,8,1,0,1,0,1,0,1,8,1,8,1
244,8,1,8,1,8,1,8,1,0,1,0,1,0,1,8,1,8,1
243,8,1,8,1,8,1,8,1,0,1,0,1,0,1,8,1,8,1
260,8,1,8,1,8,1,8,1,0,1,0,1,0,1,8,1,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,8,1,8,1,8,1,8,1,0,1,0,1,0,1,8,1,8,1
58,8,1,8,1,8,1,8,1,0,1,0,1,0,1,8,1,8,1
55,8,1,8,1,8,1,8,1,0,1,0,1,0,1,8,1,8,1
56,8,1,8,1,8,1,8,1,0,1,0,1,0,1,8,1,8,1
0,品質情報,均質番号,品質情報,均質番号,品質情報,均質番号,品質情報,均質番号,品質情報,均質番号,品質情報,均質番号,品質情報,均質番号,品質情報,均質番号,品質情報,均質番号